name: Release OdinView

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags like v0.1.0, v1.2.3, etc.

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        include:
          - os: macos-latest
            platform: mac
            artifact_name: "OdinView-${{ github.ref_name }}.dmg"
          - os: windows-latest
            platform: win
            artifact_name: "OdinView-${{ github.ref_name }}.exe"
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
          
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Run tests
        run: pnpm test
        
      - name: Build application
        run: pnpm run build:${{ matrix.platform }}
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-build
          path: release/
          
  create-release:
    needs: build-and-release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: "OdinView ${{ github.ref_name }}"
          body: |
            ## OdinView ${{ github.ref_name }}
            
            ### Downloads
            - **macOS**: Download the `.dmg` file for Mac computers
            - **Windows**: Download the `.exe` file for Windows computers
            
            ### Features
            - Secure API key management for OpenAI and Gemini
            - Local-first storage using OS keychain
            - Clean, intuitive user interface
            
            ### Installation
            - **macOS**: Open the `.dmg` file and drag OdinView to Applications
            - **Windows**: Run the `.exe` installer and follow the prompts
            
            This is an alpha release for internal testing.
          draft: false
          prerelease: true
          files: |
            ./artifacts/mac-build/**/*
            ./artifacts/win-build/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}